<div id="search-container">
    {% if not gifs %}
        <h2 id="header">
        {% if not (httpStatus == 200) %}
            Server error please try again later.
        {% else %}
            Doesn't found any gifs.
        {% endif %}
        </h2>
        <a class="btn" href="javascript:history.back()">Back</a>
    {% else %}
        {{include('gifs_nav.phtml')}}
        <div id="gifs-container">
            {% for gif in gifs %}
            <div class="gif">
                <video width="200px" autoplay loop>
                    <source src="{{ gif.images.fixed_width_small.mp4 }}" type="video/mp4">
                </video>
                <button class="like" value="{{gif.id}}"
                    {% if gif.rated.user is same as('like') %} disabled {% endif %}>
                        Like |
                        <span id="{{gif.id}}-like">
                            {% if gif.rated.like %}
                                {{ gif.rated.like }}
                            {% else %} 0 {% endif %}
                        </span>
                </button>
                <button class="dislike" value="{{gif.id}}"
                    {% if gif.rated.user is same as('dislike') %} disabled {% endif %}>
                    Dislike |
                        <span id="{{gif.id}}-dislike">
                            {% if gif.rated.dislike %}
                                {{ gif.rated.dislike }}
                            {% else %} 0 {% endif %}
                        </span>
                </button>
            </div>
            {% endfor %}
        </div>
        <script src="js/ajax.js" ></script>
    {% endif %}
</div>
