<!DOCTYPE html>
<html>
    <head>
        <title>Giphy Task</title>
        <meta charset="utf-8" />
        <link href="css/main.css" rel="stylesheet" />
        <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
    </head>
    <body>
    <form method="POST" id="search-form">
        <div class="form-container">
            <label>Search by: </label>
                <input type="text" name="phrase" id="search-phrase" value="{{input}}"/>
                <button type="submit" class="btn">Search</button>

            {% if not httpStatus == 200 %}
            <div class="error " id="error-msg">{{ meta.msg }}</div>
            {% endif %}
        </div>
        {% if not first %}
            {{ include('gifs.phtml') }}
        {% endif %}
    </form>
    </body>
</html>
