<!DOCTYPE html>
<html>
    <head>
        <title>Giphy Task</title>
        <meta charset="utf-8" />
        <link href="css/main.css" rel="stylesheet" />
        <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
    </head>
    <body>
    <div class="form-container">
        <form method="POST" id="search-form" action="index.php">
            <h2>Gifs Search engine </h2>
            <label>Search by: </label>
            <input type="text" name="phrase" id="search-phrase" value="{{phrase}}"/>
            <label> Gifs on page. </label>
            <select name="limit">
                <option value="10" {% if limit == 10 %} selected="selected" {% endif %}>
                10</option>
                <option value="20" {% if limit == 20 %} selected="selected" {% endif %}>
                20</option>
                <option value="30" {% if limit == 30 %} selected="selected" {% endif %}>
                30</option>
                <option value="50" {% if limit == 50 %} selected="selected" {% endif %}>
                50</option>
                <option value="100" {% if limit == 100 %} selected="selected" {% endif %}>
                100</option>
            </select>
            <button type="submit" class="btn">Search</button>
        </form>

            {% if not httpStatus == 200 %}
            <div class="error " id="error-msg">{{ meta.msg }}</div>
            {% endif %}
    </div>
        {% if not first_visit %}
            {{ include('gifs.phtml') }}
        {% endif %}
    </body>
</html>
